apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dm-nkp-gitops-custom-app
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`dm-nkp-gitops-custom-app.local`)
      kind: Rule
      services:
        - name: dm-nkp-gitops-custom-app
          port: 8080
  tls:
    secretName: dm-nkp-gitops-custom-app-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dm-nkp-gitops-custom-app-metrics
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dm-nkp-gitops-custom-app.local`) && PathPrefix(`/metrics`)
      kind: Rule
      services:
        - name: dm-nkp-gitops-custom-app
          port: 9090
