apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dm-nkp-gitops-custom-app
  namespace: default
spec:
  parentRefs:
    - name: traefik
      namespace: traefik-system
  hostnames:
    - dm-nkp-gitops-custom-app.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dm-nkp-gitops-custom-app
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /metrics
      backendRefs:
        - name: dm-nkp-gitops-custom-app
          port: 9090
