apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  parentRefs:
    - name: ${GATEWAY_NAME}
      namespace: ${GATEWAY_NAMESPACE}
  hostnames:
    - ${HOSTNAME}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ${APP_NAME}
          port: ${HTTP_PORT}
    - matches:
        - path:
            type: PathPrefix
            value: /metrics
      backendRefs:
        - name: ${APP_NAME}
          port: ${METRICS_PORT}

