{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dm-nkp-gitops-custom-app.fullname" . }}
  labels:
    {{- include "dm-nkp-gitops-custom-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dm-nkp-gitops-custom-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.prometheus.serviceMonitor.port | default "metrics" }}
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
      path: {{ .Values.prometheus.serviceMonitor.path }}
{{- end }}
